server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhudeming/spring-cloud-config.git
#          username:
#          passphrase:
          search-paths: SC-BOOK-CONFIG
  application:
    name: sc-configserver