server:
  port: 8074
spring:
  application:
    name: demo-client
eureka:
  client:
    prefer-same-zone-eureka: true
    region: region-west
    service-url:
      zone1: http://localhost:8763/eureka/
      zone2: http://localhost:8764/eureka/
    availability-zones:
      region-west: zone3,zone4
  instance:
    metadata-map.zone: zone4